### ISSUE TITLE
RMCS 2301 for RMCS 301X series motors

### ISSUE THREAD

**Issue by cybr17crwlr** [RCIITG/ARLE#5]
Add code for running the RMCS 301X series Quad Encoder High Torque DC motor with RMCS 2301. 
As of now it is going permanently into Error state for any possible delayMicros i.e. for all step inputs.

**Comment by eman-pars** [comment]
Found another driver **"8V-28V, 5Amp Dual DC Motor Driver with Current Sense "**
Links : 

- http://www.nex-robotics.com/products/motor-drivers/8v-28v-5amp-dual-dc-motor-driver-with-current-sense.html

- http://www.nex-robotics.com/images/downloads/8V-28V,5Amp%20Dual%20DC%20Motor%20Driver%20with%20Current%20Sense%20V2.pdf

Also there is script to use this driver on howtomechatronics.com

**Comment by cybr17crwlr** [comment]
> 
> 
> Found another driver **"8V-28V, 5Amp Dual DC Motor Driver with Current Sense "**
> Links :
> 
>     * http://www.nex-robotics.com/products/motor-drivers/8v-28v-5amp-dual-dc-motor-driver-with-current-sense.html
> 
>     * http://www.nex-robotics.com/images/downloads/8V-28V,5Amp%20Dual%20DC%20Motor%20Driver%20with%20Current%20Sense%20V2.pdf
> 
> 
> Also there is script to use this driver on howtomechatronics.com

add code for this @eman-pars in another folder in Repo

**Comment by eman-pars** [comment]
Possible problem : arduino digitalRead() too slow for rmcs 3012 encoder with 44280 counts / rev
Solution: use digitalReadFast()
Read More : http://www.arduino.cc/cgi-bin/yabb2/YaBB.pl?num=1267553811/0

**Comment by cybr17crwlr** [comment]
RMCS 301X series works without RMCS 2301 Driver. Problem resolved.
